/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lab_5_xo_gui;

import java.util.Set;

/**
 *
 * @author 65160230 Piyapong
 */
public class Lab_5_XO_GUI_JFrame extends javax.swing.JFrame {

    private XOPlayer O;
    private XOPlayer X;
    private XOBoard board;

    /**
     * Creates new form Lab_5_XO_GUI_JFrame
     */
    public Lab_5_XO_GUI_JFrame() {
        initComponents();
        //config player to variable
        O = new XOPlayer('O');
        X = new XOPlayer('X');
        load();

    }

    public void showTable() {
        char[][] table = board.getTable();
        btnPlayer1.setText(String.valueOf(table[0][0]));
        btnPlayer2.setText(String.valueOf(table[0][1]));
        btnPlayer3.setText(String.valueOf(table[0][2]));
        btnPlayer4.setText(String.valueOf(table[1][0]));
        btnPlayer5.setText(String.valueOf(table[1][1]));
        btnPlayer6.setText(String.valueOf(table[1][2]));
        btnPlayer7.setText(String.valueOf(table[2][0]));
        btnPlayer8.setText(String.valueOf(table[2][1]));
        btnPlayer9.setText(String.valueOf(table[2][2]));
    }

    public void showTrun() {
        XOPlayer currentPlayer = board.getCurrentPlayer();
        lblStatus.setText("  Turn : " + currentPlayer.getSymbol());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelOfButton = new javax.swing.JPanel();
        btnPlayer1 = new javax.swing.JButton();
        btnPlayer2 = new javax.swing.JButton();
        btnPlayer3 = new javax.swing.JButton();
        btnPlayer4 = new javax.swing.JButton();
        btnPlayer5 = new javax.swing.JButton();
        btnPlayer6 = new javax.swing.JButton();
        btnPlayer7 = new javax.swing.JButton();
        btnPlayer8 = new javax.swing.JButton();
        btnPlayer9 = new javax.swing.JButton();
        jPanelOfText = new javax.swing.JPanel();
        lblPlayerX = new javax.swing.JPanel();
        lblPlayerO = new javax.swing.JPanel();
        jPanelOfGame = new javax.swing.JPanel();
        lblStatus = new javax.swing.JLabel();
        btnNewGame = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(95, 111, 101));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanelOfButton.setBackground(new java.awt.Color(98, 114, 84));
        jPanelOfButton.setPreferredSize(new java.awt.Dimension(350, 350));

        btnPlayer1.setBackground(new java.awt.Color(201, 218, 191));
        btnPlayer1.setFont(new java.awt.Font("Sarabun", 1, 36)); // NOI18N
        btnPlayer1.setForeground(new java.awt.Color(95, 111, 101));
        btnPlayer1.setText("-");
        btnPlayer1.setOpaque(false);
        btnPlayer1.setPreferredSize(new java.awt.Dimension(105, 105));
        btnPlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayer1ActionPerformed(evt);
            }
        });

        btnPlayer2.setBackground(new java.awt.Color(201, 218, 191));
        btnPlayer2.setFont(new java.awt.Font("Sarabun", 1, 36)); // NOI18N
        btnPlayer2.setForeground(new java.awt.Color(95, 111, 101));
        btnPlayer2.setText("-");
        btnPlayer2.setOpaque(false);
        btnPlayer2.setPreferredSize(new java.awt.Dimension(105, 105));
        btnPlayer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayer2ActionPerformed(evt);
            }
        });

        btnPlayer3.setBackground(new java.awt.Color(201, 218, 191));
        btnPlayer3.setFont(new java.awt.Font("Sarabun", 1, 36)); // NOI18N
        btnPlayer3.setForeground(new java.awt.Color(95, 111, 101));
        btnPlayer3.setText("-");
        btnPlayer3.setOpaque(false);
        btnPlayer3.setPreferredSize(new java.awt.Dimension(105, 105));
        btnPlayer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayer3ActionPerformed(evt);
            }
        });

        btnPlayer4.setBackground(new java.awt.Color(201, 218, 191));
        btnPlayer4.setFont(new java.awt.Font("Sarabun", 1, 36)); // NOI18N
        btnPlayer4.setForeground(new java.awt.Color(95, 111, 101));
        btnPlayer4.setText("-");
        btnPlayer4.setOpaque(false);
        btnPlayer4.setPreferredSize(new java.awt.Dimension(105, 105));
        btnPlayer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayer4ActionPerformed(evt);
            }
        });

        btnPlayer5.setBackground(new java.awt.Color(201, 218, 191));
        btnPlayer5.setFont(new java.awt.Font("Sarabun", 1, 36)); // NOI18N
        btnPlayer5.setForeground(new java.awt.Color(95, 111, 101));
        btnPlayer5.setText("-");
        btnPlayer5.setOpaque(false);
        btnPlayer5.setPreferredSize(new java.awt.Dimension(105, 105));
        btnPlayer5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayer5ActionPerformed(evt);
            }
        });

        btnPlayer6.setBackground(new java.awt.Color(201, 218, 191));
        btnPlayer6.setFont(new java.awt.Font("Sarabun", 1, 36)); // NOI18N
        btnPlayer6.setForeground(new java.awt.Color(95, 111, 101));
        btnPlayer6.setText("-");
        btnPlayer6.setOpaque(false);
        btnPlayer6.setPreferredSize(new java.awt.Dimension(105, 105));
        btnPlayer6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayer6ActionPerformed(evt);
            }
        });

        btnPlayer7.setBackground(new java.awt.Color(201, 218, 191));
        btnPlayer7.setFont(new java.awt.Font("Sarabun", 1, 36)); // NOI18N
        btnPlayer7.setForeground(new java.awt.Color(95, 111, 101));
        btnPlayer7.setText("-");
        btnPlayer7.setOpaque(false);
        btnPlayer7.setPreferredSize(new java.awt.Dimension(105, 105));
        btnPlayer7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayer7ActionPerformed(evt);
            }
        });

        btnPlayer8.setBackground(new java.awt.Color(201, 218, 191));
        btnPlayer8.setFont(new java.awt.Font("Sarabun", 1, 36)); // NOI18N
        btnPlayer8.setForeground(new java.awt.Color(95, 111, 101));
        btnPlayer8.setText("-");
        btnPlayer8.setOpaque(false);
        btnPlayer8.setPreferredSize(new java.awt.Dimension(105, 105));
        btnPlayer8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayer8ActionPerformed(evt);
            }
        });

        btnPlayer9.setBackground(new java.awt.Color(201, 218, 191));
        btnPlayer9.setFont(new java.awt.Font("Sarabun", 1, 36)); // NOI18N
        btnPlayer9.setForeground(new java.awt.Color(95, 111, 101));
        btnPlayer9.setText("-");
        btnPlayer9.setOpaque(false);
        btnPlayer9.setPreferredSize(new java.awt.Dimension(105, 105));
        btnPlayer9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayer9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelOfButtonLayout = new javax.swing.GroupLayout(jPanelOfButton);
        jPanelOfButton.setLayout(jPanelOfButtonLayout);
        jPanelOfButtonLayout.setHorizontalGroup(
            jPanelOfButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOfButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOfButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlayer4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlayer7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelOfButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlayer5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlayer8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelOfButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPlayer9, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlayer6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelOfButtonLayout.setVerticalGroup(
            jPanelOfButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOfButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOfButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOfButtonLayout.createSequentialGroup()
                        .addComponent(btnPlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPlayer6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPlayer9, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelOfButtonLayout.createSequentialGroup()
                        .addComponent(btnPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPlayer5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPlayer8, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelOfButtonLayout.createSequentialGroup()
                        .addComponent(btnPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPlayer4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPlayer7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelOfText.setBackground(new java.awt.Color(98, 114, 84));

        lblPlayerX.setBackground(new java.awt.Color(254, 250, 224));

        javax.swing.GroupLayout lblPlayerXLayout = new javax.swing.GroupLayout(lblPlayerX);
        lblPlayerX.setLayout(lblPlayerXLayout);
        lblPlayerXLayout.setHorizontalGroup(
            lblPlayerXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        lblPlayerXLayout.setVerticalGroup(
            lblPlayerXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblPlayerO.setBackground(new java.awt.Color(254, 250, 224));

        javax.swing.GroupLayout lblPlayerOLayout = new javax.swing.GroupLayout(lblPlayerO);
        lblPlayerO.setLayout(lblPlayerOLayout);
        lblPlayerOLayout.setHorizontalGroup(
            lblPlayerOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );
        lblPlayerOLayout.setVerticalGroup(
            lblPlayerOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelOfTextLayout = new javax.swing.GroupLayout(jPanelOfText);
        jPanelOfText.setLayout(jPanelOfTextLayout);
        jPanelOfTextLayout.setHorizontalGroup(
            jPanelOfTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOfTextLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOfTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPlayerO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPlayerX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelOfTextLayout.setVerticalGroup(
            jPanelOfTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOfTextLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPlayerX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPlayerO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelOfGame.setBackground(new java.awt.Color(98, 114, 84));

        lblStatus.setBackground(new java.awt.Color(254, 250, 224));
        lblStatus.setFont(new java.awt.Font("Sarabun", 1, 24)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(95, 111, 101));
        lblStatus.setText("  Welcome to XO Game");
        lblStatus.setToolTipText("");
        lblStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblStatus.setOpaque(true);

        btnNewGame.setBackground(new java.awt.Color(254, 250, 224));
        btnNewGame.setFont(new java.awt.Font("Sarabun", 1, 18)); // NOI18N
        btnNewGame.setForeground(new java.awt.Color(95, 111, 101));
        btnNewGame.setText("New Game");
        btnNewGame.setOpaque(false);

        btnClose.setBackground(new java.awt.Color(254, 250, 224));
        btnClose.setFont(new java.awt.Font("Sarabun", 1, 18)); // NOI18N
        btnClose.setForeground(new java.awt.Color(95, 111, 101));
        btnClose.setText("Close");
        btnClose.setOpaque(false);

        javax.swing.GroupLayout jPanelOfGameLayout = new javax.swing.GroupLayout(jPanelOfGame);
        jPanelOfGame.setLayout(jPanelOfGameLayout);
        jPanelOfGameLayout.setHorizontalGroup(
            jPanelOfGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOfGameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelOfGameLayout.setVerticalGroup(
            jPanelOfGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOfGameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOfGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(lblStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNewGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelOfGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelOfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelOfText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelOfButton, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                    .addComponent(jPanelOfText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelOfGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayer1ActionPerformed
        board.setRowCol(0, 0);
        showTable();
    }//GEN-LAST:event_btnPlayer1ActionPerformed

    private void btnPlayer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayer2ActionPerformed
        board.setRowCol(0, 1);
        showTable();
    }//GEN-LAST:event_btnPlayer2ActionPerformed

    private void btnPlayer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayer3ActionPerformed
        board.setRowCol(0, 2);
        showTable();
    }//GEN-LAST:event_btnPlayer3ActionPerformed

    private void btnPlayer4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayer4ActionPerformed
        board.setRowCol(1, 0);
        showTable();
    }//GEN-LAST:event_btnPlayer4ActionPerformed

    private void btnPlayer5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayer5ActionPerformed
        board.setRowCol(1, 1);
        showTable();
    }//GEN-LAST:event_btnPlayer5ActionPerformed

    private void btnPlayer6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayer6ActionPerformed
        board.setRowCol(1, 2);
        showTable();
    }//GEN-LAST:event_btnPlayer6ActionPerformed

    private void btnPlayer7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayer7ActionPerformed
        board.setRowCol(2, 0);
        showTable();
    }//GEN-LAST:event_btnPlayer7ActionPerformed

    private void btnPlayer8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayer8ActionPerformed
        board.setRowCol(2, 1);
        showTable();
    }//GEN-LAST:event_btnPlayer8ActionPerformed

    private void btnPlayer9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayer9ActionPerformed
        board.setRowCol(2, 2);
        showTable();
    }//GEN-LAST:event_btnPlayer9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab_5_XO_GUI_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab_5_XO_GUI_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab_5_XO_GUI_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab_5_XO_GUI_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab_5_XO_GUI_JFrame().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnNewGame;
    private javax.swing.JButton btnPlayer1;
    private javax.swing.JButton btnPlayer2;
    private javax.swing.JButton btnPlayer3;
    private javax.swing.JButton btnPlayer4;
    private javax.swing.JButton btnPlayer5;
    private javax.swing.JButton btnPlayer6;
    private javax.swing.JButton btnPlayer7;
    private javax.swing.JButton btnPlayer8;
    private javax.swing.JButton btnPlayer9;
    private javax.swing.JPanel jPanelOfButton;
    private javax.swing.JPanel jPanelOfGame;
    private javax.swing.JPanel jPanelOfText;
    private javax.swing.JPanel lblPlayerO;
    private javax.swing.JPanel lblPlayerX;
    private javax.swing.JLabel lblStatus;
    // End of variables declaration//GEN-END:variables

    private void load() {
        board = new XOBoard(X, O);
        showTable();
        showTrun();
    }
}
